repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.5.0
  #   hooks:
  #     - id: end-of-file-fixer
  #       exclude: "business-facing/layer"
  #     - id: trailing-whitespace
  #       exclude: "business-facing/layer"
  #     - id: check-yaml
  #       exclude: "business-facing/layer"
  #     - id: check-json
  #       exclude: "business-facing/layer"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
      - id: ruff-format
